/* MUNDA — integrated precision-routing game controller */
(function(global){'use strict';const M=global.MUNDA,U=M;
 const Game={
  mode:null,level:1,score:0,streak:0,multiplier:1,connected:0,correctConnections:0,mistakes:0,startTime:0,puzzle:null,params:null,phase:'idle',selection:null,drag:null,machine:null,sequenceErrors:0,routeScores:[],deadline:0,training:null,seed:0,lastTick:0,
  startMode(mode,options){options=options||{};this.mode=mode;this.training=options.training||null;this.level=options.level||1;this.score=0;this.streak=0;this.multiplier=1;this.correctConnections=0;this.mistakes=0;this.machine=M.StateMachine.create('MENU');this.machine.transition('PLAYING');M.Screens.enterGame(mode);this.startLevel()},
  startLevel(){
   const daily=this.mode==='daily'?M.Daily.create(new Date()):null;if(daily)this.level=daily.level;this.seed=daily?daily.seed:(this.mode==='endless'?Math.floor(Math.random()*2147483647):(this.level*7919+(this.mode||'production').length*101));
   this.params=M.difficulty.getParams(this.level,this.mode);this.params.seed=this.seed;this.params.training=this.training;this.params.mechanics=M.Mechanics.forStage(this.level,this.mode,this.seed,this.training);
   this.connected=0;this.sequenceErrors=0;this.routeScores=[];this.selection=null;this.drag=null;this.traceAccuracy=100;
   this.beginTrace();
  },
  beginTrace(){
   // Pre-assembly: print a random MUNDA circuit by tracing its dotted outline.
   // The very first production-shift stage uses an easy shape to ease the player in.
   const easy = this.mode === 'production' && this.level <= 1;
   this.trace = M.CircuitTrace ? M.CircuitTrace.generate(this.seed + this.level * 31, easy) : null;
   this.phase='trace';this.machine.force('TRACE');
   // halt the stale board renderer so the trace owns the canvas
   M.BoardRenderer.puzzle=null;M.BoardRenderer.selection=null;M.BoardRenderer.drag=null;
   M.TraceRenderer.begin(this.trace,(acc)=>{this.traceAccuracy=acc;this.completeTrace(acc)});
   M.Screens.updateHud(this);M.Screens.setHint(M.t('hint.trace.hold'));
  },
  completeTrace(acc){
   // Apply accuracy to difficulty: higher accuracy → easier board.
   if(M.difficulty.applyTrace)this.params=M.difficulty.applyTrace(this.params,acc);
   this.puzzle=M.puzzleGen.generate(this.params,M.resolveWires());this.sequenceErrors=0;this.routeScores=[];this.stagePanic=this.mode==='panic'||this.puzzle.mechanics.active.includes('panic');this.phase=this.stagePanic?'panic':'playing';this.machine.force(this.stagePanic?'PANIC':'PLAYING');this.selection=null;this.drag=null;this.startTime=performance.now();this.deadline=this.puzzle.timerSeconds?this.startTime+this.puzzle.timerSeconds*1000:0;
   M.TraceRenderer.cancel();
   M.BoardRenderer.setPuzzle(this.puzzle,this.level);M.StripRenderer.setPuzzle(this.puzzle.count);M.Screens.setStripStatus(M.t('strip.integration'));M.Screens.updateHud(this);M.Screens.setMechanics(this.puzzle);M.Screens.setHint(this.puzzle.sequence?'SEQUENCE · '+this.puzzle.sequence.map(i=>String(i+1).padStart(2,'0')).join(' → '):M.t('hint.select'));M.Screens.showTutorialFor(this.puzzle);document.body.classList.toggle('panic-mode',this.stagePanic);document.body.classList.toggle('blackout-mode',!!this.puzzle.blackout);document.body.classList.toggle('clean-room-mode',(this.puzzle.mechanics.modifiers||[]).includes('CLEAN ROOM'));M.Screens.toast(M.t('toast.trace',{n:acc}),true);
  },
  get multiplierLabel(){return'×'+this.multiplier.toFixed(2).replace(/\.?0+$/,'')},
  canInput(){return this.machine?this.machine.canInput():this.phase==='playing'||this.phase==='panic'},
  hitTest(x,y){return M.BoardRenderer.hitTest(x,y)},
  terminal(hit){return hit.side==='left'?this.puzzle.left.find(t=>t.wire===hit.wire):this.puzzle.right.find(t=>t.wire===hit.wire)},
  unlock(hit){const term=this.terminal(hit);if(!term||!term.locked)return true;if(!term.calibration){term.calibration=1;M.Screens.setHint(M.t('hint.calib.start'));M.audio.lock?.();return false}term.locked=false;term.calibration=2;M.Screens.toast(M.t('toast.calibrated',{n:String(hit.wire+1).padStart(2,'0')}),true);M.audio.guide?.();this.haptic(8);return false},
  onPointerDown(x,y){if(!this.machine?.canInput())return;const hit=this.hitTest(x,y);if(!hit)return;if(!this.unlock(hit))return;if(this.puzzle.wires[hit.wire].connected)return;const priorSelection=this.selection;this.selection={wire:hit.wire,side:hit.side};M.BoardRenderer.setSelection(this.selection);this.drag={wire:hit.wire,side:hit.side,moved:false,x,y,lastX:x,lastY:y,priorSelection,route:[{x,y}]};M.BoardRenderer.setDrag(this.drag);if(this.puzzle.hidden)M.BoardRenderer.revealDestination(hit.wire,1100);M.Screens.setHint(M.t('hint.route'));M.audio.select()},
  onPointerMove(x,y){if(!this.canInput())return;if(!this.drag){M.BoardRenderer.setHover(x,y);return}const dx=x-this.drag.x,dy=y-this.drag.y;if(Math.hypot(dx,dy)>6)this.drag.moved=true;const route=this.drag.route||(this.drag.route=[]),last=route.at(-1);if(!last||Math.hypot(x-last.x,y-last.y)>7)route.push({x,y});const virus=M.BoardRenderer.hitTestVirusSegment(this.drag.lastX,this.drag.lastY,x,y);this.drag.lastX=x;this.drag.lastY=y;M.BoardRenderer.setDrag(this.drag);if(virus)this.virusFailure(virus)},
  cancelDrag(){this.drag=null;M.BoardRenderer.setDrag(null);M.BoardRenderer.setHover(-1,-1);M.Screens.setHint(this.selection?M.t('hint.source'):M.t('hint.select'))},
  onPointerUp(x,y){if(!this.machine?.canInput()){this.drag=null;M.BoardRenderer.setDrag(null);return}const src=this.drag;if(!src)return;src.route.push({x,y});this.drag=null;M.BoardRenderer.setDrag(null);M.BoardRenderer.setHover(-1,-1);const hit=this.hitTest(x,y);
   if(src.moved){if(hit&&hit.side!==src.side){const route=M.BoardRenderer.normalizeRoute(src.route,src.wire,src.side,hit.side);if(M.Routing.routeBlocked(route,this.pixelObstacles(),6)){M.Screens.setHint(M.t('hint.blocked'),true);M.audio.warning?.();return}if(!this.requiredGuidesMet(src.wire,route)){M.Screens.setHint(M.t('hint.guide'),true);M.audio.warning?.();return}this.attempt(src.wire,hit.wire,route)}else this.clearSelection();return}
   const prior=src.priorSelection;if(!prior){M.Screens.setHint(M.t('hint.source'));return}if(prior.wire===src.wire&&prior.side===src.side){this.clearSelection();return}if(prior.side===src.side){M.Screens.setHint(M.t('hint.update'));return}const route=M.BoardRenderer.defaultRoute(prior.wire);this.attempt(prior.wire,src.wire,route)
  },
  pixelObstacles(){return(this.puzzle.obstacles||[]).map(o=>({x:o.x*M.BoardRenderer.cssW,y:o.y*M.BoardRenderer.cssH,w:o.w*M.BoardRenderer.cssW,h:o.h*M.BoardRenderer.cssH}))},
  requiredGuidesMet(wire,route){const required=(this.puzzle.guides||[]).filter(g=>g.required&&g.wire===wire);return required.every(g=>route.some(p=>Math.hypot(p.x-g.x*M.BoardRenderer.cssW,p.y-g.y*M.BoardRenderer.cssH)<30))},
  selectByNumber(number){if(!this.machine?.canInput()||!this.puzzle)return false;const index=this.puzzle.wires.findIndex(w=>w.label===number&&!w.connected);if(index<0)return false;this.selection={wire:index,side:'left'};M.BoardRenderer.setSelection(this.selection);if(this.puzzle.hidden)M.BoardRenderer.revealDestination(index,1100);M.Screens.setHint(String(number).padStart(2,'0')+' · '+this.puzzle.wires[index].name.toUpperCase()+' · '+this.puzzle.wires[index].pattern.toUpperCase());M.audio.select();return true},
  attempt(from,to,route){if(from!==to){this.failure(from,to,'mismatch');return}if(this.puzzle.sequence&&this.puzzle.sequence[this.puzzle.sequenceCursor]!==from){this.sequenceErrors++;if(this.mode==='production'&&this.level>=16)return this.failure(from,to,'sequence');this.score=Math.max(0,this.score-75);this.streak=0;M.Screens.toast(M.t('toast.sequence',{n:String(this.puzzle.sequence[this.puzzle.sequenceCursor]+1).padStart(2,'0')}),false);this.clearSelection();return}
   if(this.puzzle.power&&this.puzzle.power.order.includes(from)){const expected=this.puzzle.power.order.find(i=>!this.puzzle.wires[i]?.connected);if(expected!==from){M.Screens.setHint(M.t('hint.power',{n:String(expected+1).padStart(2,'0')}),true);this.clearSelection();return}}
   if((this.puzzle.mechanics.modifiers||[]).includes('ZERO CROSS')){const existing=this.puzzle.wires.filter(w=>w.route).map(w=>w.route.map(p=>({x:p.x*M.BoardRenderer.cssW,y:p.y*M.BoardRenderer.cssH})));if(M.Routing.countCrossings(existing.concat([route||M.BoardRenderer.defaultRoute(from)]))>0){M.Screens.setHint(M.t('hint.zerocross'),true);M.audio.warning?.();this.clearSelection();return}}
   const w=this.puzzle.wires[from];if(w.damaged&&!w.repaired){w.repaired=true;M.BoardRenderer.repairPulse(from);M.Screens.toast(M.t('toast.continuity'),true);M.audio.repair?.();this.haptic(10);this.clearSelection();return}
   if(w.branches>1&&!w.branchReady){w.branchReady=true;M.BoardRenderer.setBranchReady(from);M.Screens.toast(M.t('toast.junction'),true);M.audio.guide?.();this.clearSelection();return}
   this.connectWire(from,route)
  },
  connectWire(index,route){const w=this.puzzle.wires[index];if(!w||w.connected)return;w.connected=true;w.route=(route||M.BoardRenderer.defaultRoute(index)).map(p=>({x:p.x/M.BoardRenderer.cssW,y:p.y/M.BoardRenderer.cssH}));this.connected++;this.correctConnections++;if(this.puzzle.sequence)this.puzzle.sequenceCursor++;const direct=Math.hypot((this.puzzle.railX2frac-this.puzzle.railXfrac)*M.BoardRenderer.cssW,(w.rightYfrac-w.leftYfrac)*M.BoardRenderer.cssH);const guides=(this.puzzle.guides||[]).filter(g=>g.wire===index);const used=guides.filter(g=>(route||[]).some(p=>Math.hypot(p.x-g.x*M.BoardRenderer.cssW,p.y-g.y*M.BoardRenderer.cssH)<30)).length;const metric=M.Routing.measure(route||M.BoardRenderer.defaultRoute(index),direct,{guidesUsed:used,optionalGuides:guides.filter(g=>g.optional).length});this.routeScores.push(metric.quality);const gained=Math.round((100+metric.quality)*this.multiplier);this.score+=gained;M.audio.connect();this.haptic(12);M.BoardRenderer.animateConnect(index);M.StripRenderer.brighten(this.connected,this.puzzle.count);M.Screens.setStripStatus(this.connected===this.puzzle.count?M.t('strip.full'):M.t('toast.remaining',{a:this.connected,b:this.puzzle.count,p:Math.round(this.connected/this.puzzle.count*100)}),this.connected===this.puzzle.count?'ok':'');M.Screens.toast(M.t('toast.circuit',{a:this.connected,b:this.puzzle.count,q:metric.quality,p:U.fmt(gained)}),true);M.Screens.updateHud(this);this.clearSelection();if(this.puzzle.major){this.puzzle.major.phase=Math.min(5,1+Math.floor(this.connected/this.puzzle.count*5));M.Screens.setMechanics(this.puzzle)}if(this.connected===this.puzzle.count)setTimeout(()=>this.completeLevel(),480)},
  haptic(pattern){if(M.state.settings.haptics&&global.navigator?.vibrate)global.navigator.vibrate(pattern)},
  updateMultiplier(){this.multiplier=1+Math.min(10,this.streak)*.25},clearSelection(){this.selection=null;M.BoardRenderer.setSelection(null);if(this.machine?.canInput())M.Screens.setHint(M.t('hint.select'))},
  tick(now){if(!this.machine?.canInput())return;this.lastTick=now;if(this.deadline){const remain=Math.max(0,(this.deadline-now)/1000);M.Screens.updateTimer(remain);if(remain<=0)this.failure(-1,-1,'timeout')}M.Screens.updateDebug(this)},
  currentRouting(){return this.routeScores.length?Math.round(this.routeScores.reduce((a,b)=>a+b,0)/this.routeScores.length):100},
  completeLevel(){if(!this.machine?.canInput())return;this.phase='complete';this.machine.force('SUCCESS');const elapsed=(performance.now()-this.startTime)/1000,routes=this.puzzle.wires.filter(w=>w.route).map(w=>w.route.map(p=>({x:p.x*M.BoardRenderer.cssW,y:p.y*M.BoardRenderer.cssH}))),crossings=M.Routing.countCrossings(routes),rating=M.Scoring.calculate({correct:this.puzzle.count,mistakes:this.mistakes,elapsed,idealSeconds:this.params.idealSeconds,routeQuality:this.currentRouting(),crossings,sequenceErrors:this.sequenceErrors});const levelBonus=500,perfectBonus=this.mistakes?0:250,speedBonus=Math.round(rating.speed*3),routingBonus=Math.round(rating.routing*4);this.score+=levelBonus+perfectBonus+speedBonus+routingBonus;this.streak++;this.updateMultiplier();this.persistResult(rating,elapsed);M.audio.complete();this.haptic([12,35,18]);M.BoardRenderer.completeAnimation(()=>{if(this.phase!=='complete')return;M.StripRenderer.illuminate(true);this.machine.force('RESULTS');M.Screens.showQC({mode:this.mode,level:this.level,connections:this.connected+'/'+this.puzzle.count,errors:this.mistakes,score:this.score,levelBonus,perfectBonus,speedBonus,routingBonus,streak:this.streak,multiplier:this.multiplier,elapsed,rating,crossings,major:!!this.puzzle.major})})},
  persistResult(rating,elapsed){const p=M.state.progress;p.highestLevel=this.mode==='production'?Math.max(p.highestLevel,this.level):p.highestLevel;p.bestScore=this.mode==='production'?Math.max(p.bestScore,this.score):p.bestScore;p.endlessBest=this.mode==='endless'?Math.max(p.endlessBest,this.score):p.endlessBest;p.endlessLongest=this.mode==='endless'?Math.max(p.endlessLongest,this.level):p.endlessLongest;p.runsCompleted++;p.totalConnections+=this.puzzle.count;if(rating.precision===100)p.perfectBoards++;if(this.puzzle.major)p.majorCompleted++;p.ratedBoards=(p.ratedBoards||0)+1;p.averagePrecision=Math.round(((p.averagePrecision||0)*(p.ratedBoards-1)+rating.precision)/p.ratedBoards);p.averageRouting=Math.round(((p.averageRouting||0)*(p.ratedBoards-1)+rating.routing)/p.ratedBoards);p.rank=M.Scoring.rank(p);if(this.mode==='daily'){const key=M.Daily.seedFor(new Date());const old=p.dailyResults[key]||{};p.dailyResults[key]={completed:true,score:Math.max(old.score||0,this.score),grade:rating.grade,bestTime:old.bestTime?Math.min(old.bestTime,elapsed):elapsed}}M.storage.saveProgress(p)},
  nextLevel(){this.level++;this.machine.force('TRANSITION');this.startLevel();M.audio.click()},
  failure(a,b,reason){if(!this.machine?.canInput())return;this.phase='failed';this.machine.force('FAILURE');this.mistakes++;M.state.progress.totalMistakes++;M.storage.saveProgress(M.state.progress);const done=()=>{if(this.phase!=='failed')return;M.StripRenderer.illuminate(false);M.audio.fail();this.machine.force('RESULTS');M.Screens.showFailure({mode:this.mode,level:this.level,score:this.score,streak:this.streak,mistakes:this.mistakes,reason:reason||'mismatch',best:this.mode==='production'?M.state.progress.bestScore:M.state.progress.endlessBest})};if(a>=0)M.BoardRenderer.failureSequence(a,b,done);else setTimeout(done,180)},
  virusFailure(h){if(!this.canInput())return;this.phase='failed';if(this.machine)this.machine.force('FAILURE');this.mistakes++;this.drag=null;this.selection=null;M.BoardRenderer.setDrag(null);M.BoardRenderer.setSelection(null);M.Screens.setHint(M.t('hint.virus'),true);M.BoardRenderer.virusFailureSequence(h,()=>{M.StripRenderer.illuminate(false);M.audio.fail();if(this.machine)this.machine.force('RESULTS');M.Screens.showFailure({mode:this.mode,level:this.level,score:this.score,streak:this.streak,mistakes:this.mistakes,reason:'virus',best:M.state.progress.bestScore})})},
  restartRun(){this.score=0;this.streak=0;this.multiplier=1;this.level=1;this.correctConnections=0;this.machine.force('TRANSITION');this.startLevel();M.Screens.hideModal();M.audio.click()},
  pause(toggle){if(['complete','failed'].includes(this.phase))return;if(toggle){this.prePausePhase=this.phase;this.phase='paused';this.machine.force('PAUSED');M.Screens.showPause()}else{this.phase=this.prePausePhase==='trace'?'trace':(this.stagePanic?'panic':'playing');this.machine.force(this.phase==='trace'?'TRACE':(this.stagePanic?'PANIC':'PLAYING'));M.Screens.hidePause();if(this.deadline)this.deadline=performance.now()+Math.max(1,this.puzzle.timerSeconds)*1000}}
 };
 M.game=Game;
})(typeof window!=='undefined'?window:this);
