/* MUNDA — deterministic progression and mechanic budget */
(function(global){'use strict';const M=global.MUNDA=global.MUNDA||{};
 function rng(seed){let x=(seed|0)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
 const COST={guides:1,obstacles:2,sequence:2,moving:2,damaged:2,locks:2,timed:3,split:3,power:4,hidden:4,decoys:2,blackout:2};
 const MODIFIERS=['ZERO CROSS','MEMORY','CLEAN ROOM','RUSH ORDER','BLACKOUT','MOVING LINE','PERFECT SHIFT','ROUTE MASTER','LOCKDOWN'];
 function production(level){const a=[];if(level>=4)a.push('crossings');if(level>=7)a.push('obstacles');if(level===10||level===20||level===50)a.push('major');if(level>=11)a.push('guides','sequence');if(level>=15)a.push('moving');if(level===19)a.push('panic');if(level>=21)a.push('damaged','locks');if(level>=26)a.push('timed');if(level>=31)a.push('split');if(level>=36)a.push('power');if(level>=41)a.push('hidden','decoys');if(level>=46)a.push('blackout');return[...new Set(a)]}
 function endless(level,seed){const resolvedSeed=seed||level*2654435761,random=rng(resolvedSeed);let budget=Math.min(24,Math.max(0,Math.floor(level*1.25)-3));const pool=Object.keys(COST).sort(()=>random()-.5);const active=['crossings'];for(const name of pool){if(COST[name]<=budget&&random()>.32){active.push(name);budget-=COST[name]}}const modifiers=level>=5?[MODIFIERS[Math.abs(resolvedSeed)%MODIFIERS.length]]:[];if(modifiers.includes('MEMORY')&&!active.includes('hidden'))active.push('hidden');if(modifiers.includes('BLACKOUT')&&!active.includes('blackout'))active.push('blackout');if(modifiers.includes('MOVING LINE')&&!active.includes('moving'))active.push('moving');if(modifiers.includes('LOCKDOWN')&&!active.includes('locks'))active.push('locks');let timerSeconds=active.includes('timed')?Math.max(10,26-level*.35):modifiers.includes('RUSH ORDER')?Math.max(14,30-level*.3):0;if(active.includes('hidden')&&active.includes('moving')&&timerSeconds&&timerSeconds<12)timerSeconds=12;return{active,modifiers,budget:Math.floor(level*1.25),timerSeconds,seed:resolvedSeed}}
 function forStage(level,mode,seed,training){level=Math.max(1,level|0);let active,modifiers=[];if(mode==='production')active=production(level);else if(mode==='panic'){active=['panic','timed'].concat(level>1?['moving','locks']:[]);modifiers=['RUSH ORDER']}else if(mode==='training')active=training&&training!=='basic'?[training]:[];else if(mode==='daily'){const plan=endless(18,seed);active=plan.active;modifiers=[MODIFIERS[Math.abs(seed||level)%MODIFIERS.length]]}else return endless(level,seed);return{active,modifiers,budget:level,timerSeconds:active.includes('panic')?Math.max(18,42-level*2):active.includes('timed')?Math.max(12,30-level*.35):0,seed:seed||level}}
 M.Mechanics={forStage,COST,MODIFIERS,rng};
})(typeof window!=='undefined'?window:this);
