/* MUNDA — seeded procedural assembly generation with validation retries */
(function(global){'use strict';const M=global.MUNDA,U=M;
 function shuffle(items,random){const a=items.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
 function selectColorIds(n,unused,random){return shuffle(M.WIRE_CATALOG.map(w=>w.id),random||Math.random).slice(0,n)}
 function positions(n,random,noise){const top=.1,bottom=.92,spacing=(bottom-top)/n;return Array.from({length:n},(_,i)=>Math.max(top+.005,Math.min(bottom-.005,top+spacing*(i+.5)+(random()*2-1)*spacing*.34*(noise||0))))}
 function makeObstacleRoutes(wires,obstacles){return wires.map((w,i)=>{const a={x:.13,y:w.leftYfrac},b={x:.87,y:w.rightYfrac};if(!obstacles.length)return[a,b];const o=obstacles[0],top=Math.max(.07,o.y-.07),bottom=Math.min(.95,o.y+o.h+.07),safe=(i%2?bottom:top);return[a,{x:o.x-.06,y:safe},{x:o.x+o.w+.06,y:safe},b]})}
 function build(params,resolved,seed){const random=M.Mechanics.rng(seed),n=params.wires,mechanics=params.mechanics||M.Mechanics.forStage(params.level,params.mode,seed,params.training);const ids=selectColorIds(n,0,random),rightOrder=shuffle(ids,random),leftY=positions(n,random,params.routeNoise),rightY=positions(n,random,params.routeNoise);const colors=Object.fromEntries(resolved.map(w=>[w.id,w]));const wires=[],left=[],right=[];
  for(let i=0;i<n;i++){const c=colors[ids[i]],rightSlot=rightOrder.indexOf(ids[i]);const wire={index:i,colorId:c.id,name:c.name,base:c.base,dark:c.dark,glow:c.glow,sym:c.sym,pattern:c.pattern||'solid',stiffness:c.stiffness||.88,leftYfrac:leftY[i],rightYfrac:rightY[rightSlot],connected:false,error:false,label:i+1,damaged:mechanics.active.includes('damaged')&&i<Math.max(1,Math.floor(n/3)),repaired:false,branches:mechanics.active.includes('split')&&i===0?2:1};wires.push(wire);left.push({slot:i,wire:i,yfrac:leftY[i],colorId:c.id,locked:mechanics.active.includes('locks')&&i%3===0});}
  for(let slot=0;slot<n;slot++){const wire=wires.findIndex(w=>w.colorId===rightOrder[slot]);right.push({slot,wire,yfrac:rightY[slot],colorId:rightOrder[slot],locked:mechanics.active.includes('locks')&&wire%3===0,motion:mechanics.active.includes('moving')?{type:wire%2?'track':'oscillate',amplitude:.035,speed:.00045+wire*.00003,phase:wire}:null})}
  const obstacles=mechanics.active.includes('obstacles')?[{id:'housing-0',type:'CIRCUIT HOUSING',x:.44,y:.32,w:.12,h:.34}]:[];

  const routes=makeObstacleRoutes(wires,obstacles.slice(0,1));
  const guides=mechanics.active.includes('guides')?wires.slice(0,Math.min(3,n)).map((w,i)=>({id:'guide-'+i,type:i%2?'TEXTILE CLIP':'CABLE GUIDE',x:routes[i].length>2?routes[i][1].x:.5,y:routes[i].length>2?routes[i][1].y:(w.leftYfrac+w.rightYfrac)/2,wire:i,required:i===0,optional:i!==0})):[];
  const sequence=mechanics.active.includes('sequence')?shuffle(wires.map(w=>w.index),random):null;
  const decoys=mechanics.active.includes('decoys')?[{x:.78,y:.5,sym:'ring',clue:'NO INDEX',fake:true}]:[];
  return{count:n,wires,left,right,railXfrac:.13,railX2frac:.87,leftRail:.13,rightRail:.87,params:Object.assign({},params,{seed,mechanics}),mechanics,obstacles,guides,routes,sequence,sequenceCursor:0,decoys,hidden:mechanics.active.includes('hidden'),blackout:mechanics.active.includes('blackout'),timerSeconds:mechanics.timerSeconds||0,power:mechanics.active.includes('power')?{limit:3,order:[0,2,1]}:null,splitters:mechanics.active.includes('split')?[{wire:0,x:.52,y:.5,branches:2}]:[],major:mechanics.active.includes('major')?{phase:1,totalPhases:5}:null,validation:null};
 }
 function generate(params,resolved){const base=params.seed||((params.level||1)*7919+(params.mode||'production').length*101);for(let attempt=0;attempt<24;attempt++){const puzzle=build(params,resolved,base+attempt);const check=M.PuzzleValidator?M.PuzzleValidator.validate(puzzle):{valid:true,errors:[]};puzzle.validation=check;if(check.valid)return puzzle}throw new Error('Unable to generate a verified assembly board')}
 M.puzzleGen={generate,selectColorIds};
})(typeof window!=='undefined'?window:this);
